name: dbtc
description: Do not break the chain

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cloud_firestore:
  firebase_auth:
  intl:
  rxdart: ^0.22.0
  equatable: ^0.6.0
  flutter_bloc: ^1.0.0
  bloc: ^1.0.0
  table_calendar: ^2.1.0
  flutter_local_notifications:
  flutter_localizations:
      sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - lang/en.json
